/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/desenheTheme.ts
 * Command: astryx theme build src/theme/desenheTheme.ts
 * Generated: 2026-07-03T19:55:43.167Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const desenheTheme: DefinedTheme;
